In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
obj = pd.Series([4,7,-5,3])

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2['a']

-5

In [9]:
obj2['d'] = 6

obj2[['a','c','d']]

a   -5
c    3
d    6
dtype: int64

In [10]:
obj2[obj2 > 3]

d    6
b    7
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

False

In [16]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [17]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 = pd.Series(sdata, index=states)

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [20]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [21]:
obj4.name = 'population'

obj4.index.name = 'state'

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [22]:
obj.index = ['Bob', 'Steve', 'Will', 'Ryan']

obj

Bob      4
Steve    7
Will    -5
Ryan     3
dtype: int64

In [23]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [24]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [25]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [27]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [29]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [32]:
frame2.loc['four']

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

In [33]:
frame2['debt'] = 16.2

frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.2
two    2001    Ohio  1.7  16.2
three  2002    Ohio  3.6  16.2
four   2001  Nevada  2.4  16.2
five   2002  Nevada  2.9  16.2
six    2003  Nevada  3.2  16.2

In [34]:
frame2['debt'] = np.arange(6)

In [35]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [36]:
val = pd.Series([-1.2, -1.3, -1.5], index=['two', 'three', 'five'])

frame2['debt'] = val

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  -1.3
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -1.5
six    2003  Nevada  3.2   NaN

In [37]:
frame2['eastern'] = frame2.state == 'Ohio'

frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6  -1.3     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9  -1.5    False
six    2003  Nevada  3.2   NaN    False

In [38]:
del frame2['eastern']

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  -1.3
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -1.5
six    2003  Nevada  3.2   NaN

In [39]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3 = pd.DataFrame(pop)

frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [40]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [42]:
pd.DataFrame(pop, index=[2000, 2001, 2002])

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [43]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [44]:
frame3.columns.name = 'state'
frame3.index.name = 'year'

frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [45]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [46]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, -1.3],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [48]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

obj

a    0
b    1
c    2
dtype: int64

In [49]:
index = obj.index

index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
index[1]

'b'

In [51]:
labels = pd.Index(np.arange(3))

labels

Int64Index([0, 1, 2], dtype='int64')

In [52]:
obj2 = pd.Series([-1.5, -2.5, -3.5], index=labels)

obj2

0   -1.5
1   -2.5
2   -3.5
dtype: float64

In [53]:
obj2.index is labels

True

In [54]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [55]:
'Ohio' in frame3.columns

True

In [56]:
2001 in frame3.index

True

In [57]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [4]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj.reindex(['a', 'b', 'c', 'd'])

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [6]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [7]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [8]:
obj3.reindex([0,1,2,3,4,5], method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [9]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'], columns=['Ohio', 'Texas', 'California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [10]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [11]:
states = ['Texas', 'Utah', 'California']

frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [15]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])

obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [16]:
new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [17]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int64

In [18]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [19]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
data.drop(['Colorado', 'Utah'])

one  two  three  four
Ohio        0    1      2     3
New York   12   13     14    15

In [21]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [23]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [26]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [27]:
data.drop('three', axis=1, inplace=True)

In [28]:
data

one  two  four
Ohio        0    1     3
Colorado    4    5     7
Utah        8    9    11
New York   12   13    15

In [29]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [30]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [31]:
obj['b']

1.0

In [32]:
obj[1]

1.0

In [33]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [34]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [35]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [37]:
obj[[2,3]]

c    2.0
d    3.0
dtype: float64

In [39]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [40]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [41]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [42]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [43]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [44]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [45]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [47]:
data[:3]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [48]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [49]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [50]:
data[data<5] = 0

In [51]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [54]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [55]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [56]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [57]:
data.iloc[[1,3], [3,0,1]]

four  one  two
Colorado     7    0    5
New York    15   12   13

In [58]:
data.loc[:'Utah', 'one':'three']

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10

In [59]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [60]:
data.iloc[:, :3][data > 0]

one   two  three
Ohio       NaN   NaN    NaN
Colorado   NaN   5.0    6.0
Utah       8.0   9.0   10.0
New York  12.0  13.0   14.0

In [61]:
data.iloc[:, :3][data.three > 0]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [64]:
data.at['Colorado', 'two']

5

In [65]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [66]:
ser[-1]

KeyError: -1

In [67]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [68]:
ser2[-1]

2.0

In [69]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [2]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.4, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2

a   -2.1
c    3.6
e   -1.4
f    4.0
g    3.1
dtype: float64

In [5]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.1
f    NaN
g    NaN
dtype: float64

In [6]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [7]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [8]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [9]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [10]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [11]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [12]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4,5)), columns=list('abcde'))

df2.loc[1, 'b'] = np.nan

In [13]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [14]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [15]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [16]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [17]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [18]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [19]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [20]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr[0]

array([0, 1, 2, 3])

In [22]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [24]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

series = frame.iloc[0]

In [25]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [26]:
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [27]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [28]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [29]:
series3 = frame['d']

In [30]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [31]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [32]:
frame.sub(series3, axis='index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [33]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.800765  0.717128  0.406313
Ohio   -1.087785  0.968753 -1.200711
Texas   0.305896  1.229777 -1.663409
Oregon -2.805988  1.392461 -0.104822

In [34]:
np.abs(frame)

b         d         e
Utah    0.800765  0.717128  0.406313
Ohio    1.087785  0.968753  1.200711
Texas   0.305896  1.229777  1.663409
Oregon  2.805988  1.392461  0.104822

In [35]:
f = lambda x: x.max() - x.min()

frame.apply(f)

b    3.606753
d    0.675333
e    2.069722
dtype: float64

In [36]:
frame.apply(f, axis='columns')

Utah      0.394452
Ohio      2.169464
Texas     2.893186
Oregon    4.198449
dtype: float64

In [37]:
def f(x):
    return pd.Series([x.max(), x.min()], index=['max', 'min'])

frame.apply(f)

b         d         e
max  0.800765  1.392461  0.406313
min -2.805988  0.717128 -1.663409

In [39]:
format = lambda x: '%.2f' % x

frame.applymap(format)

b     d      e
Utah     0.80  0.72   0.41
Ohio    -1.09  0.97  -1.20
Texas    0.31  1.23  -1.66
Oregon  -2.81  1.39  -0.10

In [40]:
frame['e'].map(format)

Utah       0.41
Ohio      -1.20
Texas     -1.66
Oregon    -0.10
Name: e, dtype: object

In [41]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [42]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [43]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [44]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [45]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [46]:
obj = pd.Series([4, 7, -3, 2])

obj

0    4
1    7
2   -3
3    2
dtype: int64

In [47]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [48]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [49]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [50]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [51]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [53]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [54]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [55]:
obj.index.is_unique

False

In [56]:
obj['a']

a    0
a    1
dtype: int64

In [57]:
obj['c']

4

In [58]:
df = pd.DataFrame(np.random.randn(4,3), index=['a', 'a', 'b', 'b'])

df

0         1         2
a -0.270926 -1.151617 -0.249240
a -0.128525 -1.813056  0.234098
b  1.112379 -1.039738  0.442495
b  0.548328 -0.666428 -0.192814

In [59]:
df.loc['b']

0         1         2
b  1.112379 -1.039738  0.442495
b  0.548328 -0.666428 -0.192814

In [2]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'],
                 columns=['one', 'two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [3]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [4]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [5]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [6]:
df.idxmax()

one    b
two    d
dtype: object

In [7]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [8]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [9]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [10]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [11]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [12]:
conda install pandas-datareader

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 23.7.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-datareader-0.10.0   |     pyhd3eb1b0_0          71 KB
    ------------------------------------------------------------
                                           Total:          71 KB

The following NEW packages will be INSTALLED:

  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.10.0-pyhd3eb1b0_0



pandas-datareader-0. | 71 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to us

In [15]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

uniques = obj.unique()

uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [16]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [17]:
pd.value_counts(obj.values, sort=False)

c    3
d    1
a    3
b    2
dtype: int64

In [18]:
mask = obj.isin(['b', 'c'])

In [19]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [20]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [21]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

unique_vals = pd.Series(['c', 'a', 'b'])

pd.Index(unique_vals).get_indexer(to_match)

array([0, 1, 2, 2, 0, 1])

In [22]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [23]:
result = data.apply(pd.value_counts).fillna(0)

result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0